/*
 * Copyright (c) 2010, 2026 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.services.process.replace;

import java.io.Serial;

import jakarta.annotation.Generated;

import org.eclipse.scout.rt.platform.Replace;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import formdata.shared.IFormDataInterface03;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "formdata.client.ui.forms.replace.ExtendedExtendedForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ExtendedExtendedFormData extends ExtendedFormData {

  @Serial
  private static final long serialVersionUID = 1L;

  public IgnoringGroupBoxExCreateNone getIgnoringGroupBoxExCreateNone() {
    return getFieldByClass(IgnoringGroupBoxExCreateNone.class);
  }

  public IgnoringGroupBoxExNoneCreate getIgnoringGroupBoxExNoneCreate() {
    return getFieldByClass(IgnoringGroupBoxExNoneCreate.class);
  }

  public NameExEx getNameExEx() {
    return getFieldByClass(NameExEx.class);
  }

  public SdkCommandCreateCreateCreate getSdkCommandCreateCreateCreate() {
    return getFieldByClass(SdkCommandCreateCreateCreate.class);
  }

  public SdkCommandCreateCreateIgnore getSdkCommandCreateCreateIgnore() {
    return getFieldByClass(SdkCommandCreateCreateIgnore.class);
  }

  public SdkCommandCreateCreateNone getSdkCommandCreateCreateNone() {
    return getFieldByClass(SdkCommandCreateCreateNone.class);
  }

  public SdkCommandCreateCreateUse getSdkCommandCreateCreateUse() {
    return getFieldByClass(SdkCommandCreateCreateUse.class);
  }

  public SdkCommandCreateIgnoreCreate getSdkCommandCreateIgnoreCreate() {
    return getFieldByClass(SdkCommandCreateIgnoreCreate.class);
  }

  public SdkCommandCreateIgnoreIgnore getSdkCommandCreateIgnoreIgnore() {
    return getFieldByClass(SdkCommandCreateIgnoreIgnore.class);
  }

  public SdkCommandCreateIgnoreNone getSdkCommandCreateIgnoreNone() {
    return getFieldByClass(SdkCommandCreateIgnoreNone.class);
  }

  public SdkCommandCreateIgnoreUse getSdkCommandCreateIgnoreUse() {
    return getFieldByClass(SdkCommandCreateIgnoreUse.class);
  }

  public SdkCommandCreateNoneCreate getSdkCommandCreateNoneCreate() {
    return getFieldByClass(SdkCommandCreateNoneCreate.class);
  }

  public SdkCommandCreateNoneIgnore getSdkCommandCreateNoneIgnore() {
    return getFieldByClass(SdkCommandCreateNoneIgnore.class);
  }

  public SdkCommandCreateNoneNone getSdkCommandCreateNoneNone() {
    return getFieldByClass(SdkCommandCreateNoneNone.class);
  }

  public SdkCommandCreateNoneUse getSdkCommandCreateNoneUse() {
    return getFieldByClass(SdkCommandCreateNoneUse.class);
  }

  public SdkCommandCreateUseCreate getSdkCommandCreateUseCreate() {
    return getFieldByClass(SdkCommandCreateUseCreate.class);
  }

  public SdkCommandCreateUseIgnore getSdkCommandCreateUseIgnore() {
    return getFieldByClass(SdkCommandCreateUseIgnore.class);
  }

  public SdkCommandCreateUseNone getSdkCommandCreateUseNone() {
    return getFieldByClass(SdkCommandCreateUseNone.class);
  }

  public SdkCommandCreateUseUse getSdkCommandCreateUseUse() {
    return getFieldByClass(SdkCommandCreateUseUse.class);
  }

  public SdkCommandIgnoreCreateCreate getSdkCommandIgnoreCreateCreate() {
    return getFieldByClass(SdkCommandIgnoreCreateCreate.class);
  }

  public SdkCommandIgnoreCreateIgnore getSdkCommandIgnoreCreateIgnore() {
    return getFieldByClass(SdkCommandIgnoreCreateIgnore.class);
  }

  public SdkCommandIgnoreCreateNone getSdkCommandIgnoreCreateNone() {
    return getFieldByClass(SdkCommandIgnoreCreateNone.class);
  }

  public SdkCommandIgnoreCreateUse getSdkCommandIgnoreCreateUse() {
    return getFieldByClass(SdkCommandIgnoreCreateUse.class);
  }

  public SdkCommandIgnoreIgnoreCreate getSdkCommandIgnoreIgnoreCreate() {
    return getFieldByClass(SdkCommandIgnoreIgnoreCreate.class);
  }

  public SdkCommandIgnoreIgnoreUse getSdkCommandIgnoreIgnoreUse() {
    return getFieldByClass(SdkCommandIgnoreIgnoreUse.class);
  }

  public SdkCommandIgnoreNoneCreate getSdkCommandIgnoreNoneCreate() {
    return getFieldByClass(SdkCommandIgnoreNoneCreate.class);
  }

  public SdkCommandIgnoreNoneUse getSdkCommandIgnoreNoneUse() {
    return getFieldByClass(SdkCommandIgnoreNoneUse.class);
  }

  public SdkCommandIgnoreUseCreate getSdkCommandIgnoreUseCreate() {
    return getFieldByClass(SdkCommandIgnoreUseCreate.class);
  }

  public SdkCommandIgnoreUseIgnore getSdkCommandIgnoreUseIgnore() {
    return getFieldByClass(SdkCommandIgnoreUseIgnore.class);
  }

  public SdkCommandIgnoreUseNone getSdkCommandIgnoreUseNone() {
    return getFieldByClass(SdkCommandIgnoreUseNone.class);
  }

  public SdkCommandIgnoreUseUse getSdkCommandIgnoreUseUse() {
    return getFieldByClass(SdkCommandIgnoreUseUse.class);
  }

  public SdkCommandNoneCreateCreate getSdkCommandNoneCreateCreate() {
    return getFieldByClass(SdkCommandNoneCreateCreate.class);
  }

  public SdkCommandNoneCreateIgnore getSdkCommandNoneCreateIgnore() {
    return getFieldByClass(SdkCommandNoneCreateIgnore.class);
  }

  public SdkCommandNoneCreateNone getSdkCommandNoneCreateNone() {
    return getFieldByClass(SdkCommandNoneCreateNone.class);
  }

  public SdkCommandNoneCreateUse getSdkCommandNoneCreateUse() {
    return getFieldByClass(SdkCommandNoneCreateUse.class);
  }

  public SdkCommandNoneIgnoreCreate getSdkCommandNoneIgnoreCreate() {
    return getFieldByClass(SdkCommandNoneIgnoreCreate.class);
  }

  public SdkCommandNoneIgnoreIgnore getSdkCommandNoneIgnoreIgnore() {
    return getFieldByClass(SdkCommandNoneIgnoreIgnore.class);
  }

  public SdkCommandNoneIgnoreNone getSdkCommandNoneIgnoreNone() {
    return getFieldByClass(SdkCommandNoneIgnoreNone.class);
  }

  public SdkCommandNoneIgnoreUse getSdkCommandNoneIgnoreUse() {
    return getFieldByClass(SdkCommandNoneIgnoreUse.class);
  }

  public SdkCommandNoneNoneCreate getSdkCommandNoneNoneCreate() {
    return getFieldByClass(SdkCommandNoneNoneCreate.class);
  }

  public SdkCommandNoneNoneIgnore getSdkCommandNoneNoneIgnore() {
    return getFieldByClass(SdkCommandNoneNoneIgnore.class);
  }

  public SdkCommandNoneNoneNone getSdkCommandNoneNoneNone() {
    return getFieldByClass(SdkCommandNoneNoneNone.class);
  }

  public SdkCommandNoneNoneUse getSdkCommandNoneNoneUse() {
    return getFieldByClass(SdkCommandNoneNoneUse.class);
  }

  public SdkCommandNoneUseCreate getSdkCommandNoneUseCreate() {
    return getFieldByClass(SdkCommandNoneUseCreate.class);
  }

  public SdkCommandNoneUseIgnore getSdkCommandNoneUseIgnore() {
    return getFieldByClass(SdkCommandNoneUseIgnore.class);
  }

  public SdkCommandNoneUseNone getSdkCommandNoneUseNone() {
    return getFieldByClass(SdkCommandNoneUseNone.class);
  }

  public SdkCommandNoneUseUse getSdkCommandNoneUseUse() {
    return getFieldByClass(SdkCommandNoneUseUse.class);
  }

  public SdkCommandUseCreateCreate getSdkCommandUseCreateCreate() {
    return getFieldByClass(SdkCommandUseCreateCreate.class);
  }

  public SdkCommandUseCreateIgnore getSdkCommandUseCreateIgnore() {
    return getFieldByClass(SdkCommandUseCreateIgnore.class);
  }

  public SdkCommandUseCreateNone getSdkCommandUseCreateNone() {
    return getFieldByClass(SdkCommandUseCreateNone.class);
  }

  public SdkCommandUseCreateUse getSdkCommandUseCreateUse() {
    return getFieldByClass(SdkCommandUseCreateUse.class);
  }

  public SdkCommandUseIgnoreCreate getSdkCommandUseIgnoreCreate() {
    return getFieldByClass(SdkCommandUseIgnoreCreate.class);
  }

  public SdkCommandUseIgnoreIgnore getSdkCommandUseIgnoreIgnore() {
    return getFieldByClass(SdkCommandUseIgnoreIgnore.class);
  }

  public SdkCommandUseIgnoreNone getSdkCommandUseIgnoreNone() {
    return getFieldByClass(SdkCommandUseIgnoreNone.class);
  }

  public SdkCommandUseIgnoreUse getSdkCommandUseIgnoreUse() {
    return getFieldByClass(SdkCommandUseIgnoreUse.class);
  }

  public SdkCommandUseNoneCreate getSdkCommandUseNoneCreate() {
    return getFieldByClass(SdkCommandUseNoneCreate.class);
  }

  public SdkCommandUseNoneIgnore getSdkCommandUseNoneIgnore() {
    return getFieldByClass(SdkCommandUseNoneIgnore.class);
  }

  public SdkCommandUseNoneNone getSdkCommandUseNoneNone() {
    return getFieldByClass(SdkCommandUseNoneNone.class);
  }

  public SdkCommandUseNoneUse getSdkCommandUseNoneUse() {
    return getFieldByClass(SdkCommandUseNoneUse.class);
  }

  public SdkCommandUseUseCreate getSdkCommandUseUseCreate() {
    return getFieldByClass(SdkCommandUseUseCreate.class);
  }

  public SdkCommandUseUseIgnore getSdkCommandUseUseIgnore() {
    return getFieldByClass(SdkCommandUseUseIgnore.class);
  }

  public SdkCommandUseUseNone getSdkCommandUseUseNone() {
    return getFieldByClass(SdkCommandUseUseNone.class);
  }

  public SdkCommandUseUseUse getSdkCommandUseUseUse() {
    return getFieldByClass(SdkCommandUseUseUse.class);
  }

  @Replace
  public static class IgnoringGroupBoxExCreateNone extends IgnoringGroupBoxExCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class IgnoringGroupBoxExNoneCreate extends AbstractValueFieldData<String> {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class NameExEx extends NameEx {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * access method for property StringProperty.
     */
    public String getStringProperty() {
      return getStringPropertyProperty().getValue();
    }

    /**
     * access method for property StringProperty.
     */
    public void setStringProperty(String stringProperty) {
      getStringPropertyProperty().setValue(stringProperty);
    }

    public StringPropertyProperty getStringPropertyProperty() {
      return getPropertyByClass(StringPropertyProperty.class);
    }

    public static class StringPropertyProperty extends AbstractPropertyData<String> {

      @Serial
      private static final long serialVersionUID = 1L;
    }
  }

  @Replace
  public static class SdkCommandCreateCreateCreate extends SdkCommandCreateCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateCreateIgnore extends SdkCommandCreateCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateCreateNone extends SdkCommandCreateCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateCreateUse extends SdkCommandCreateCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateIgnoreCreate extends SdkCommandCreateIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateIgnoreIgnore extends SdkCommandCreateIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateIgnoreNone extends SdkCommandCreateIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateIgnoreUse extends SdkCommandCreateIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateNoneCreate extends SdkCommandCreateNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateNoneIgnore extends SdkCommandCreateNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateNoneNone extends SdkCommandCreateNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateNoneUse extends SdkCommandCreateNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateUseCreate extends SdkCommandCreateUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateUseIgnore extends SdkCommandCreateUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateUseNone extends SdkCommandCreateUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandCreateUseUse extends SdkCommandCreateUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreCreateCreate extends SdkCommandIgnoreCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreCreateIgnore extends SdkCommandIgnoreCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreCreateNone extends SdkCommandIgnoreCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreCreateUse extends SdkCommandIgnoreCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreIgnoreCreate extends AbstractValueFieldData<String> {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreIgnoreUse extends UsingFormFieldData {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreNoneCreate extends AbstractValueFieldData<String> {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreNoneUse extends UsingFormFieldData {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreUseCreate extends SdkCommandIgnoreUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreUseIgnore extends SdkCommandIgnoreUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreUseNone extends SdkCommandIgnoreUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandIgnoreUseUse extends SdkCommandIgnoreUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneCreateCreate extends SdkCommandNoneCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneCreateIgnore extends SdkCommandNoneCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneCreateNone extends SdkCommandNoneCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneCreateUse extends SdkCommandNoneCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneIgnoreCreate extends SdkCommandNoneIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneIgnoreIgnore extends SdkCommandNoneIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneIgnoreNone extends SdkCommandNoneIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneIgnoreUse extends SdkCommandNoneIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneNoneCreate extends SdkCommandNoneNone implements IFormDataInterface03 {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneNoneIgnore extends SdkCommandNoneNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneNoneNone extends SdkCommandNoneNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneNoneUse extends SdkCommandNoneNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneUseCreate extends SdkCommandNoneUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneUseIgnore extends SdkCommandNoneUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneUseNone extends SdkCommandNoneUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandNoneUseUse extends SdkCommandNoneUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseCreateCreate extends SdkCommandUseCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseCreateIgnore extends SdkCommandUseCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseCreateNone extends SdkCommandUseCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseCreateUse extends SdkCommandUseCreate {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseIgnoreCreate extends SdkCommandUseIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseIgnoreIgnore extends SdkCommandUseIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseIgnoreNone extends SdkCommandUseIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseIgnoreUse extends SdkCommandUseIgnore {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseNoneCreate extends SdkCommandUseNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseNoneIgnore extends SdkCommandUseNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseNoneNone extends SdkCommandUseNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseNoneUse extends SdkCommandUseNone {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseUseCreate extends SdkCommandUseUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseUseIgnore extends SdkCommandUseUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseUseNone extends SdkCommandUseUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class SdkCommandUseUseUse extends SdkCommandUseUse {

    @Serial
    private static final long serialVersionUID = 1L;
  }
}
