/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.ui.forms;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.util.concurrent.IRunnable;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

import formdata.shared.SharedAnnotation;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "formdata.client.ui.forms.AnnotationCopyTestForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AnnotationCopyTestFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public First getFirst() {
    return getFieldByClass(First.class);
  }

  @SharedAnnotation(type = IRunnable.class)
  public static class First extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
