/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.extension;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;

import formdata.shared.services.process.SimpleTableFormData;
import formdata.shared.services.process.SimpleTableFormData.TestTable.TestTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(SimpleTableFormData.class)
@Generated(value = "formdata.client.extensions.SimpleTableFormExtensionWithTable", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SimpleTableFormExtensionWithTableData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  @Extends(TestTableRowData.class)
  public static class TestTableFieldExtensionRowData implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String contributed = "contributed";
    private BigDecimal m_contributed;

    public BigDecimal getContributed() {
      return m_contributed;
    }

    public void setContributed(BigDecimal newContributed) {
      m_contributed = newContributed;
    }
  }
}
