/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.extension;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;

import formdata.shared.services.process.SimpleTableFormData.TestTable.TestTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(TestTableRowData.class)
@Generated(value = "formdata.client.extensions.SimpleTableFormExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SimpleTableFormExtensionData implements Serializable {

  private static final long serialVersionUID = 1L;
  public static final String myExtension = "myExtension";
  private BigDecimal m_myExtension;

  public BigDecimal getMyExtension() {
    return m_myExtension;
  }

  public void setMyExtension(BigDecimal newMyExtension) {
    m_myExtension = newMyExtension;
  }
}
