/*
 * Copyright (c) 2010, 2026 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.scope.extended;

import java.io.Serial;

import jakarta.annotation.Generated;

import org.eclipse.scout.rt.platform.Replace;

import formdata.shared.scope.field.AbstractScopeTestGroupBoxData.Process;
import formdata.shared.scope.orig.ScopeTestFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Replace
@Generated(value = "formdata.client.scope.extended.ExtendedScopeTestForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ExtendedScopeTestFormData extends ScopeTestFormData {

  @Serial
  private static final long serialVersionUID = 1L;

  public AnliegenBox getAnliegenBox() {
    return getFieldByClass(AnliegenBox.class);
  }

  public ExtendedProcess getExtendedProcess() {
    return getFieldByClass(ExtendedProcess.class);
  }

  @Replace
  public static class AnliegenBox extends ProcessesBox {

    @Serial
    private static final long serialVersionUID = 1L;
  }

  @Replace
  public static class ExtendedProcess extends Process {

    @Serial
    private static final long serialVersionUID = 1L;
  }
}
