/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package formdata.shared.ui.forms;

import javax.annotation.Generated;

import org.eclipse.scout.commons.IRunnable;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

import formdata.client.ClientAnnotation;
import formdata.shared.SharedAnnotation;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "FormDataUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AnnotationCopyTestFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AnnotationCopyTestFormData() {
  }

  public First getFirst() {
    return getFieldByClass(First.class);
  }

  @ClientAnnotation
  @SharedAnnotation(type = IRunnable.class)
  public static class First extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public First() {
    }
  }
}
