/*******************************************************************************
 * Copyright (c) 2010 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.sdk.ui.wizard.bundle;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.jface.viewers.LabelProvider;
import org.eclipse.pde.core.plugin.IPluginModelBase;
import org.eclipse.pde.core.plugin.PluginRegistry;
import org.eclipse.scout.sdk.ScoutSdkCore;
import org.eclipse.scout.sdk.Texts;
import org.eclipse.scout.sdk.operation.project.BundleImportOperation;
import org.eclipse.scout.sdk.ui.fields.StyledTextField;
import org.eclipse.scout.sdk.ui.fields.proposal.ContentProposalEvent;
import org.eclipse.scout.sdk.ui.fields.proposal.IProposalAdapterListener;
import org.eclipse.scout.sdk.ui.fields.proposal.ProposalTextField;
import org.eclipse.scout.sdk.ui.fields.proposal.StaticContentProvider;
import org.eclipse.scout.sdk.ui.internal.ScoutSdkUi;
import org.eclipse.scout.sdk.ui.wizard.AbstractWorkspaceWizardPage;
import org.eclipse.scout.sdk.util.typecache.IWorkingCopyManager;
import org.eclipse.swt.events.ModifyEvent;
import org.eclipse.swt.events.ModifyListener;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

/**
 * <h3> {@link BundleImportWizardPage}</h3> ...
 * TODO find a better way to import bundles. Probably
 */
public class BundleImportWizardPage extends AbstractWorkspaceWizardPage {

  // ui fields
  private StyledTextField m_projectIdField;
  private ProposalTextField m_pluginModelField;

  // members
  private String m_projectId;
  private IPluginModelBase m_pluginModel;

  // process members
  private boolean m_projectIdFieldEnabled = true;
  private boolean m_projectAliasFieldEnabled = true;
  private boolean m_autoGeneratedProjectId = true;
  private boolean m_autoGeneratedAlias = true;

  public BundleImportWizardPage() {
    super(BundleImportWizardPage.class.getName());
    setTitle(Texts.get("ImportScoutBundle"));
    setDescription(Texts.get("BundleImportDesc"));
  }

  @Override
  protected void createContent(Composite parent) {
    IPluginModelBase[] workspaceModels = PluginRegistry.getWorkspaceModels();
    ArrayList<IPluginModelBase> proposals = new ArrayList<IPluginModelBase>();
    for (IPluginModelBase pluginModel : workspaceModels) {
      IProject p = pluginModel.getUnderlyingResource().getProject();
      if (ScoutSdkCore.getScoutWorkspace().getScoutBundle(p) == null) {
        proposals.add(pluginModel);
      }
    }

    m_pluginModelField = getFieldToolkit().createProposalField(parent, Texts.get("PluginToImport"));
    ILabelProvider labelProvider = new P_PluginDescLabelProvider();
    m_pluginModelField.setLabelProvider(labelProvider);
    m_pluginModelField.setContentProvider(new StaticContentProvider(proposals.toArray(new Object[proposals.size()]), labelProvider));

    // m_pluginModelField.acceptProposal(m_superType);
    m_pluginModelField.addProposalAdapterListener(new IProposalAdapterListener() {
      @Override
      public void proposalAccepted(ContentProposalEvent event) {
        try {
          setStateChanging(true);
          setPluginSelectionInternal((IPluginModelBase) event.proposal);
        }
        finally {
          setStateChanging(false);
        }
      }
    });

    m_projectIdField = getFieldToolkit().createStyledTextField(parent, Texts.get("ScoutProjectId"));
    m_projectIdField.setText(getProjectId());
    m_projectIdField.setEnabled(isProjectIdFieldEnabled());
    m_projectIdField.addModifyListener(new ModifyListener() {

      @Override
      public void modifyText(ModifyEvent e) {
        m_projectId = m_projectIdField.getText();
        pingStateChanging();
      }
    });

    // layout
    parent.setLayout(new GridLayout(1, true));

    m_pluginModelField.setLayoutData(new GridData(GridData.GRAB_HORIZONTAL | GridData.FILL_HORIZONTAL));
    m_projectIdField.setLayoutData(new GridData(GridData.GRAB_HORIZONTAL | GridData.FILL_HORIZONTAL));
  }

  private int LEGACY_PROJECT_ID = 1 << 1;
  private int LEGACY_BUNDLE_TYPE = 1 << 3;

  private void setPluginSelectionInternal(IPluginModelBase proposal) {
    if (proposal != null) {
      Matcher m = Pattern.compile("^(([^.]*\\.)*)([^.]*)\\.(client|ui\\.swt\\.app|ui\\.swt|ui\\.swing|shared|server\\.app | server).*$").matcher(proposal.getBundleDescription().getName());
      if (m.find()) {
        String id = m.group(1);
        if (id.length() > 0) {
          id = id.substring(0, id.length() - 1);
        }
        setProjectId(id);
      }
    }
    m_pluginModel = proposal;
  }

  @Override
  public boolean performFinish(IProgressMonitor monitor, IWorkingCopyManager workingCopyManager) throws CoreException {
    BundleImportOperation operation = new BundleImportOperation();
    operation.setProjectId(getProjectId());
    operation.setPluginModel(getPluginModel());
    operation.run(monitor, workingCopyManager);
    return true;
  }

  public void setProjectId(String projectId) {
    try {
      setStateChanging(true);
      setProjectIdInternal(projectId);
      m_autoGeneratedProjectId = false;
    }
    finally {
      setStateChanging(false);
    }
  }

  private void setProjectIdInternal(String projectId) {
    m_projectId = projectId;
    if (isControlCreated()) {
      m_projectIdField.setText(projectId);
    }
  }

  public String getProjectId() {
    return m_projectId;
  }

  public void setPluginModel(IPluginModelBase pluginModel) {
    m_pluginModel = pluginModel;
  }

  public IPluginModelBase getPluginModel() {
    return m_pluginModel;
  }

  public void setProjectIdFieldEnabled(boolean projectIdFieldEnabled) {
    m_projectIdFieldEnabled = projectIdFieldEnabled;
    if (isControlCreated()) {
      m_projectIdField.setEnabled(projectIdFieldEnabled);
    }
  }

  public boolean isProjectIdFieldEnabled() {
    return m_projectIdFieldEnabled;
  }

  // @Override
  // protected void validatePage(MultiStatus multiStatus){
  // try{
  // // multiStatus.add(getStatusNameField());
  // }
  // catch(JavaModelException e){
  // SDEUI.logError("could not validate name field.", e);
  // }
  // }

  // protected IStatus getStatusNameField() throws JavaModelException{
  // if(StringUtility.isNullOrEmpty(getBundleName())||getBundleName().equals(getParentBundle().getScoutProject().getGroupId())){
  // return new Status(IStatus.ERROR, SDE.PLUGIN_ID, Texts.get("Error_fieldNull"));
  // }
  // // check not allowed names
  // if(ResourcesPlugin.getWorkspace().getRoot().getProject(getBundleName()) != null){
  // return new Status(IStatus.ERROR, SDE.PLUGIN_ID, Texts.get("Error_nameAlreadyUsed"));
  // }
  // if(!getBundleName().matches("[a-zA-Z0-9\\._-]*")){
  // return new Status(IStatus.ERROR, SDE.PLUGIN_ID, Texts.get("Error_invalidFieldX", getBundleName()));
  // }
  // else{
  // return Status.OK_STATUS;
  // }
  // }

  private class P_PluginDescLabelProvider extends LabelProvider {
    @Override
    public String getText(Object element) {
      IPluginModelBase pluginModel = (IPluginModelBase) element;
      return pluginModel.getBundleDescription().getName();
    }

    @Override
    public Image getImage(Object element) {
      return ScoutSdkUi.getImage(ScoutSdkUi.SharedBundle);
    }
  }
}
