/*******************************************************************************
 * Copyright (c) 2017 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package formdata.shared.extension;

import java.io.Serializable;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;

import formdata.shared.services.process.AbstractAddressTableFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(AbstractAddressTableFieldData.class)
@Generated(value = "formdata.client.extensions.ExtensionToAbstractTableFieldTemplate", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ExtensionToAbstractTableFieldTemplateData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public static class CustomAbstractAdvisorTableFieldTableExtensionRowData implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String added = "added";
    private Boolean m_added;

    public Boolean getAdded() {
      return m_added;
    }

    public void setAdded(Boolean newAdded) {
      m_added = newAdded;
    }
  }
}
