/*******************************************************************************
 * Copyright (c) 2015 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package formdata.shared.extension;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.commons.annotations.Extends;

import formdata.shared.services.process.SimpleTableFormData.TestTable.TestTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(TestTableRowData.class)
@Generated(value = "formdata.client.extensions.SimpleTableFormExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SimpleTableFormExtensionData implements Serializable {

  private static final long serialVersionUID = 1L;
  public static final String myExtension = "myExtension";
  private BigDecimal m_myExtension;

  public SimpleTableFormExtensionData() {
  }

  public BigDecimal getMyExtension() {
    return m_myExtension;
  }

  public void setMyExtension(BigDecimal myExtension) {
    m_myExtension = myExtension;
  }
}
