/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.services.process;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "formdata.client.ui.forms.UsingTemplateForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UsingTemplateFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ExternalGroupBox getExternalGroupBox() {
    return getFieldByClass(ExternalGroupBox.class);
  }

  public InternalHtml getInternalHtml() {
    return getFieldByClass(InternalHtml.class);
  }

  public TestCheckbox getTestCheckbox() {
    return getFieldByClass(TestCheckbox.class);
  }

  public TestLimitedString getTestLimitedString() {
    return getFieldByClass(TestLimitedString.class);
  }

  public static class ExternalGroupBox extends AbstractExternalGroupBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class InternalHtml extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class TestCheckbox extends AbstractTestCheckboxFieldData {

    private static final long serialVersionUID = 1L;
  }

  public static class TestLimitedString extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
