<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010, 2025 BSI Business Systems Integration AG
  ~
  ~ This program and the accompanying materials are made
  ~ available under the terms of the Eclipse Public License 2.0
  ~ which is available at https://www.eclipse.org/legal/epl-2.0/
  ~
  ~ SPDX-License-Identifier: EPL-2.0
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- NO PARENT HERE BY DESIGN -->
  <!-- So that this helper pom is not published to central -->

  <!--
  New Eclipse platform instructions:
   1. Adapt the Eclipse P2 target file in org.eclipse.scout.sdk-target/org.eclipse.YEAR-MONTH-dependencies.target to the new release:
      1. Change the name of this .target file according to the new Eclipse release.
      2. In the file change "name", "sequenceNumber" and "repository location".
      3. Sometimes some artifacts needs to be removed/added so that the new target platform resolves successfully (will be verified later in step 5).
   2. In org.eclipse.scout.sdk-target/pom.xml adjust the file name and classifier for the artifact attached with "build-helper-maven-plugin".
   3. In org.eclipse.scout.sdk.p2/pom.xml adjust the dependency classifier for the "org.eclipse.scout.sdk-target" artifact in the "target-platform-configuration" to the one used in the previous step.
   4. In org.eclipse.scout.sdk-feature: Update the P2 update site in *.properties and feature.xml.
   5. Verify using local Maven build on org.eclipse.scout.sdk.p2/pom.xml using "mvn clean install" and fix issues.

   6. In org.eclipse.scout.sdk/pom.xml adjust dependency versions in the section titled "dependencies to Eclipse artifacts". The version should match the one of the corresponding Eclipse release.
   7. In org.eclipse.scout.sdk/pom.xml adjust dependency versions in the section titled "versions to dependencies uploaded by scout". The version should match the one of the corresponding Eclipse release.
   8. In the child modules of this pom adjust the source P2 repository (id and url) in the "tycho-p2-extras-plugin" configuration.
   9. In the child modules of this pom adjust the version of the pom to the ones used in step 7.
  10. In the child modules of this pom adjust all the dependency versions to match the versions used in step 6.
  11. Verify using local Maven build on this pom: "mvn clean install -Dmaster_sanityCheck_skip=true -Dmaster_flatten_skip=true -Prelease -Pcentral-portal"
  12. Verify using local Maven build on org.eclipse.scout.sdk/pom.xml using "mvn clean install -DskipTests".
  13. If successful: Commit and push as feature branch to GitHub.

  14. Run job https://ci.eclipse.org/scout/job/org.eclipse.scout.sdk.deps_deploy/ on your branch.
  15. After successful Job completion publish the artifact to Maven Central by doing ONE of the following:
      1. Using Web-UI: a) Visit https://central.sonatype.com/publishing/deployments (requires login).
                       b) Wait until the deployment appears. This may take several hours up to several days to appear!
                       c) Check if Maven Central validation passed.
                       d) Manually check the content.
                       e) Publish the artifacts if all ok.
      2. Using Rest-API (this can be done immediately after deployment, there is no need to wait for the deployment to appear in the web UI)
         See https://central.sonatype.org/publish/publish-portal-api/ for authentication instructions and commands to check status, publish or drop the deployment.
         The deploymentId required in the rest calls can be copied from the console output at the end of the Jenkins job "org.eclipse.scout.sdk.deps_deploy".
         To validate the uploaded content check the zip in the build artifacts of the Jenkins job: https://ci.eclipse.org/scout/job/org.eclipse.scout.sdk.deps_deploy/lastSuccessfulBuild/artifact/org.eclipse.scout.sdk.s2e.releng/
  16. After publishing on Maven Central run job https://ci.eclipse.org/scout/job/org.eclipse.scout.sdk.branch-14.0_continuous/ on your branch.
  17. If successful: Merge your branch.
  -->
  <groupId>org.eclipse.scout.sdk</groupId>
  <artifactId>org.eclipse.scout.sdk.s2e.releng</artifactId>
  <version>14.0.0-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>${project.artifactId}</name>

  <properties>
    <!-- don't deploy this helper pom -->
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

  <modules>
    <module>org.eclipse.m2e.core</module>
    <module>org.eclipse.m2e.core.ui</module>
  </modules>

</project>
