/*
 * Copyright (c) 2010, 2023 BSI Business Systems Integration AG
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
package formdata.shared.extension;

import java.io.Serializable;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;

import formdata.shared.services.process.AbstractAddressTableFieldData;
import formdata.shared.services.process.AbstractAddressTableFieldData.AbstractAddressTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(AbstractAddressTableFieldData.class)
@Generated(value = "formdata.client.extensions.ExtensionToAbstractTableFieldTemplate", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ExtensionToAbstractTableFieldTemplateData extends AbstractFormFieldData {
  private static final long serialVersionUID = 1L;

  @Extends(AbstractAddressTableRowData.class)
  public static class RowData implements Serializable {
    private static final long serialVersionUID = 1L;
    public static final String added = "added";
    private Boolean m_added;

    public Boolean getAdded() {
      return m_added;
    }

    public void setAdded(Boolean newAdded) {
      m_added = newAdded;
    }
  }
}
