/*
 * Copyright (c) 2010-2020 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 */
package formdata.shared.extension;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;

import formdata.shared.services.process.SimpleTableFormData;
import formdata.shared.services.process.SimpleTableFormData.TestTable.TestTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(SimpleTableFormData.class)
@Generated(value = "formdata.client.extensions.SimpleTableFormExtensionWithTable", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class SimpleTableFormExtensionWithTableData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  @Extends(TestTableRowData.class)
  public static class TestTableFieldExtensionRowData implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String contributed = "contributed";
    private BigDecimal m_contributed;

    public BigDecimal getContributed() {
      return m_contributed;
    }

    public void setContributed(BigDecimal newContributed) {
      m_contributed = newContributed;
    }
  }
}
