/*
 * Copyright (c) 2016 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 */
package formdata.shared.scope.orig;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

import formdata.shared.scope.field.AbstractScopeTestGroupBoxData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "formdata.client.scope.orig.ScopeTestForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ScopeTestFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ProcessesBox getProcessesBox() {
    return getFieldByClass(ProcessesBox.class);
  }

  public static class ProcessesBox extends AbstractScopeTestGroupBoxData {

    private static final long serialVersionUID = 1L;
  }
}
