package org.eclipse.scout.sdk.s2i.settings;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class ScoutSettingsForm {
  private JCheckBox autoUpdateDerivedResources;
  private JComboBox cboLogLevel;
  private JLabel lblLogLevel;
  private JPanel rootPanel;

  public JCheckBox getAutoUpdateDerivedResources() {
    return autoUpdateDerivedResources;
  }

  public JComboBox getLogLevel() {
    return cboLogLevel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
    rootPanel.putClientProperty("html.disable", Boolean.TRUE);
    rootPanel.setBorder(BorderFactory.createTitledBorder("Settings for the Scout SDK"));
    autoUpdateDerivedResources = new JCheckBox();
    autoUpdateDerivedResources.setSelected(true);
    autoUpdateDerivedResources.setText("Automatically update generated classes");
    autoUpdateDerivedResources.putClientProperty("html.disable", Boolean.TRUE);
    rootPanel.add(autoUpdateDerivedResources, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(264, 24), null, 0, false));
    final Spacer spacer1 = new Spacer();
    rootPanel.add(spacer1, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    lblLogLevel = new JLabel();
    lblLogLevel.setText("Log Level");
    lblLogLevel.putClientProperty("html.disable", Boolean.TRUE);
    rootPanel.add(lblLogLevel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(82, 16), null, 0, false));
    cboLogLevel = new JComboBox();
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    defaultComboBoxModel1.addElement("Error");
    defaultComboBoxModel1.addElement("Warning");
    defaultComboBoxModel1.addElement("Info");
    defaultComboBoxModel1.addElement("Debug");
    cboLogLevel.setModel(defaultComboBoxModel1);
    cboLogLevel.putClientProperty("html.disable", Boolean.TRUE);
    rootPanel.add(cboLogLevel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }
}
